from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)
from reportlab.lib.styles import getSampleStyleSheet
from datetime import datetime

import translation

FIELD_LABELS = {

    "name": "Full Name",
    "age": "Age",
    "gender": "Gender",
    "weight": "Weight",
    "height": "Height",
    "bmi": "BMI",

    "cholesterol_total": "Total Cholesterol",
    "ldl": "LDL Cholesterol",
    "hdl": "HDL Cholesterol",
    "triglycerides": "Triglycerides",
    "fasting_blood_sugar": "Fasting Blood Sugar",
    "hba1c": "HbA1c",
    "resting_bp_systolic": "Systolic Blood Pressure",
    "smoker_status": "Smoking Status",

    "prediction_text": "Prediction Result"

}


def create_pdf(patient):

    filename = f"report_{patient.get('name','Patient')}.pdf"

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    story = []

    # ==========================
    # HEADER
    # ==========================

    story.append(
        Paragraph(
            "<b><font size=20>HealthVibe AI</font></b>",
            styles["Title"]
        )
    )

    story.append(
        Paragraph(
            translation.t("Clinical Decision Support Report"),
            styles["Heading2"]
        )
    )

    story.append(Spacer(1,20))

    # ==========================
    # PATIENT INFO
    # ==========================

    story.append(
        Paragraph(
            f"<b>{translation.t('Patient:')}</b> {patient.get('name','-')}",
            styles["BodyText"]
        )
    )

    story.append(
        Paragraph(
            f"<b>{translation.t('Age:')}</b> {patient.get('age','-')}",
            styles["BodyText"]
        )
    )

    story.append(
        Paragraph(
            f"<b>{translation.t('Gender:')}</b> {patient.get('gender','-')}",
            styles["BodyText"]
        )
    )

    story.append(
        Paragraph(
            f"<b>{translation.t('Date:')}</b> {datetime.now().strftime('%d/%m/%Y %H:%M')}",
            styles["BodyText"]
        )
    )

    story.append(Spacer(1,20))

    # ==========================
    # RESULT
    # ==========================

    story.append(
        Paragraph(
            f"<b>{translation.t('AI Prediction')}</b>",
            styles["Heading1"]
        )
    )

    story.append(
        Paragraph(
            translation.t(str(patient.get("prediction","-"))),
            styles["Heading2"]
        )
    )

    story.append(
        Paragraph(
            f"{translation.t('Confidence : ')}{round(patient.get('probability',0)*100,1)} %",
            styles["BodyText"]
        )
    )

    story.append(Spacer(1,20))

    # ==========================
    # ALL PATIENT DATA
    # ==========================

    story.append(
        Paragraph(
            f"<b>{translation.t('Clinical Data')}</b>",
            styles["Heading2"]
        )
    )

    ignore = [
        "prediction",
        "probability"
    ]

    for key, value in patient.items():

        if key in ignore:
            continue

        label = translation.t(FIELD_LABELS.get(key, key))

        story.append(
            Paragraph(
                f"{label} : {value}",
                styles["BodyText"]
            )
        )

    story.append(Spacer(1,20))

    story.append(
        Paragraph(
            translation.t("Generated by HealthVibe AI"),
            styles["Italic"]
        )
    )

    doc.build(story)

    return filename