from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)
from reportlab.lib.styles import getSampleStyleSheet
from datetime import datetime


def create_pdf(patient):

    filename = f"report_{patient.get('name','Patient')}.pdf"

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    story = []

    # ==========================
    # HEADER
    # ==========================

    story.append(
        Paragraph(
            "<b><font size=20>HealthVibe AI</font></b>",
            styles["Title"]
        )
    )

    story.append(
        Paragraph(
            "Clinical Decision Support Report",
            styles["Heading2"]
        )
    )

    story.append(Spacer(1,20))

    # ==========================
    # PATIENT INFO
    # ==========================

    story.append(
        Paragraph(
            f"<b>Patient:</b> {patient.get('name','-')}",
            styles["BodyText"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Age:</b> {patient.get('age','-')}",
            styles["BodyText"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Gender:</b> {patient.get('gender','-')}",
            styles["BodyText"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Date:</b> {datetime.now().strftime('%d/%m/%Y %H:%M')}",
            styles["BodyText"]
        )
    )

    story.append(Spacer(1,20))

    # ==========================
    # RESULT
    # ==========================

    story.append(
        Paragraph(
            "<b>AI Prediction</b>",
            styles["Heading1"]
        )
    )

    story.append(
        Paragraph(
            str(patient.get("prediction","-")),
            styles["Heading2"]
        )
    )

    story.append(
        Paragraph(
            f"Confidence : {round(patient.get('probability',0)*100,1)} %",
            styles["BodyText"]
        )
    )

    story.append(Spacer(1,20))

    # ==========================
    # ALL PATIENT DATA
    # ==========================

    story.append(
        Paragraph(
            "<b>Clinical Data</b>",
            styles["Heading2"]
        )
    )

    ignore = [
        "prediction",
        "probability"
    ]

    for key, value in patient.items():

        if key in ignore:
            continue

        story.append(
            Paragraph(
                f"{key} : {value}",
                styles["BodyText"]
            )
        )

    story.append(Spacer(1,20))

    story.append(
        Paragraph(
            "Generated by HealthVibe AI",
            styles["Italic"]
        )
    )

    doc.build(story)

    return filename