import streamlit as st
import pandas as pd
import numpy as np
import fpdf
from fpdf import FPDF
import io

# دالة لتوليد تقرير الـ PDF بالشكل الطبي والمُنظم
def generate_pdf(user_data, result, recommendations):
    pdf = FPDF()
    pdf.add_page()
    
    # عنوان التقرير الرئيسي
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(200, 10, "HealthVibe AI - Thrombosis Risk Assessment Report", ln=True, align='C')
    pdf.ln(10)
    
    # قسم بيانات المريض والمدخلات الطبية
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(200, 10, "Patient Input Parameters:", ln=True)
    pdf.set_font("Arial", '', 11)
    for key, value in user_data.items():
        pdf.cell(200, 8, f" - {key}: {value}", ln=True)
    
    pdf.ln(5)
    
    # قسم النتيجة وتوقع الموديل
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(200, 10, "Assessment Result:", ln=True)
    pdf.set_font("Arial", 'B', 14)
    if result == "High Risk / Positive":
        pdf.set_text_color(200, 0, 0) # لور أحمر لو النتيجة إيجابية بالمرض
    else:
        pdf.set_text_color(0, 150, 0) # لون أخضر لو النتيجة سليمة
    pdf.cell(200, 10, f" Status: {result}", ln=True)
    
    # إعادة لون الخط للأسود الطبيعي
    pdf.set_text_color(0, 0, 0)
    pdf.ln(5)
    
    # قسم التوصيات والنصائح الطبية بناء على النتيجة
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(200, 10, "Medical Recommendations & Health Advice:", ln=True)
    pdf.set_font("Arial", '', 11)
    for rec in recommendations:
        pdf.multi_cell(180, 8, f" - {rec}")
        
    # إخلاء مسؤولية طبي في أسفل التقرير
    pdf.ln(20)
    pdf.set_font("Arial", 'I', 9)
    pdf.multi_cell(0, 5, "Disclaimer: This report is generated by an AI model for educational and screening purposes only. It does not replace professional medical diagnosis. Please consult a doctor immediately if you feel unwell.")
    
    return bytes(pdf.output())

# إعدادات الصفحة الخاصة بـ Streamlit والأيقونة
st.set_page_config(page_title="Thrombosis Assessment", page_icon="🩸")

st.title("🩸 Thrombosis Risk Assessment & AI Screening")
st.write("Enter the patient health parameters below to analyze the risk of Thrombosis (Blood Clots).")

# بناء الاستمارة (Form) ليدخل المريض بياناته
with st.form("thrombosis_form"):
    col1, col2 = st.columns(2)
    with col1:
        age = st.number_input("Age", min_value=1, max_value=120, value=45)
        d_dimer = st.number_input("D-Dimer Level (ng/mL)", min_value=0.0, value=250.0, help="Normal is typically < 500 ng/mL")
        swelling = st.selectbox("Leg Swelling / Edema", ["No", "Yes"])
    with col2:
        pain = st.selectbox("Leg Pain / Tenderness", ["No", "Yes"])
        history = st.selectbox("Previous History of Blood Clots", ["No", "Yes"])
        mobility = st.selectbox("Recent Prolonged Immobility (Bed rest/Long travel)", ["No", "Yes"])
        
    submit = st.form_submit_button("Analyze Risk Status")

# عند ضغط زر التحليل وحساب النتيجة
if submit:
    # منطق حسابي يحاكي فحص الـ AI وقواعد Wells' Score الطبية
    risk_score = 0
    if d_dimer > 500: risk_score += 2
    if swelling == "Yes": risk_score += 1
    if pain == "Yes": risk_score += 1
    if history == "Yes": risk_score += 2
    if mobility == "Yes": risk_score += 1
    if age > 60: risk_score += 1
    
    user_data = {
        "Age": age,
        "D-Dimer Level": f"{d_dimer} ng/mL",
        "Leg Swelling": swelling,
        "Leg Pain": pain,
        "Previous History": history,
        "Prolonged Immobility": mobility
    }
    
    st.subheader("Analysis Results")
    
    # التحقق من حالة المريض وعرض التوصيات المناسبة
    if risk_score >= 3 or d_dimer > 500:
        result_status = "High Risk / Positive"
        st.error(f"⚠️ Result: {result_status}")
        recs = [
            "Please consult a cardiovascular specialist or visit an emergency room immediately.",
"Avoid sitting or standing still for long periods; keep your legs slightly elevated when resting.",
            "Do not massage the affected leg, as this could dislodge a potential clot.",
            "An ultrasound (Doppler) or further clinical imaging is highly recommended to confirm diagnosis."
        ]
    else:
        result_status = "Low Risk / Negative"
        st.success(f"✅ Result: {result_status}")
        recs = [
            "Maintain an active lifestyle with regular walking or exercise.",
            "Stay well-hydrated throughout the day to support healthy blood flow.",
            "If taking long flights or trips, remember to stretch and move your legs every 1-2 hours.",
            "Keep monitoring for any sudden symptoms like swelling, redness, or shortness of breath."
        ]
        
    st.write("Recommendations:")
    for r in recs:
        st.write(f"- {r}")
        
    # توليد ملف الـ PDF وحفظه في الذاكرة للتحميل
    pdf_bytes = generate_pdf(user_data, result_status, recs)
    
    # زر تحميل التقرير الطبي بصيغة PDF
    st.download_button(
        label="📥 Download PDF Medical Report",
        data=pdf_bytes,
        file_name="Thrombosis_AI_Report.pdf",
        mime="application/pdf"
    )